project:
  type: website

website:
  title: "Human learning Machine Learning"
  navbar:
    right:
      - about.ipynb
      - text: "Github"
        href: https://github.com/steeleestes
      - text: "Hugging Face"
        href: https://huggingface.co/krptk
format:
  html:
    theme: slate
    css: styles.css



